### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by tobedecided0601** [JinPots/Facebook60FPS-Re-Encoder#8]
- [x] Rendering screen got bugged after getting an error.

- [x] Also the result screen will immediately shows that it has finished rendering even though it's not.

**Comment by JinPots** [comment]
ol

**Comment by tobedecided0601** [comment]
ayo the one above isn't fixed
this issue has not merged

**Comment by JinPots** [comment]
wait what

**Comment by tobedecided0601** [comment]
the fix is still on my fork

**Comment by tobedecided0601** [comment]
Issue resolved in #9.
